### ISSUE TITLE
Set up travis

### ISSUE THREAD

**Issue by mcollina** [davidmarkclements/fast-safe-stringify#11]

**Comment by watson** [comment]
@davidmarkclements can I help out?

**Comment by davidmarkclements** [comment]
Of course! Be my guest - I'll add you to org 

Could also do with coverage stats etc

**Comment by watson** [comment]
Hmm... It doesn't seem that I'm allowed to set up this project on Travis even though I'm a collaborator 😞

**Comment by mcollina** [comment]
This should be done.
