### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by BridgeAR** [davidmarkclements/fast-safe-stringify#26]
As far as I see it the current benchmarks are not ideal. It would be great to have something similar like the Node.js benchmarks where they are over and over and a significance is shown as well. Something similar is done when using https://www.npmjs.com/package/benchmark.

Should we switch to that?

**Comment by mcollina** [comment]
Yes and no. 
The current approach was copied over from pino, as benchmark is almost useless because of I/O.
Moreover, benchmark impacts heavily the V8 call stack, and it skew the results.

Overall, I'd say 👍  for this repository. However, I'm not really satisfied with both.

**Comment by BridgeAR** [comment]
Resolved with v.2

Closing
