### ISSUE TITLE
[ts] Cannot invoke an expression whose type lacks a call signature

### ISSUE THREAD

**Issue by nvtuan305** [davidmarkclements/fast-safe-stringify#36]
Hello,
I got this error with `tslint`. The below code still work but I got the error warning with `tslint`.

> [ts] Cannot invoke an expression whose type lacks a call signature. Type 'typeof import("../node_modules/fast-safe-stringify/index' has no compatible call signatures.

Here is my code
```javascript
const stringify = require('fast-safe-stringify');
const info = { message: 'Message from John...' };
console.log(stringify(info));
```
- fast-safe-stringify: v2.0.4
- tslint: v5.10.0
- Typescript: 2.9.2

**Comment by davidmarkclements** [comment]
Hi @nvtuan305 any typescript suppport we have has been contributed by typescipters. If you get to the bottom of your problem are PR is more than welcome however I don't consider this a fast-safe-stringify issue as much as a typescript ecosystem problem - closing for now
