### ISSUE TITLE
tarball data for fast-safe-stringify eems to be corrupted. Trying again.

### ISSUE THREAD

**Issue by anuragkumar19** [davidmarkclements/fast-safe-stringify#55]
npm WARN tarball tarball data for fast-safe-stringify@https://registry.npmjs.org/fast-safe-stringify/-/fast-safe-stringify-2.0.8.tgz (sha512-lXatBjf3WPjmWD6DpIZxkeSsCOwqI0maYMpgDlx8g4U2qi4lbjA9oH/HD2a87G+KfsUmo5WbJFmqBZlPxtptag==) seems to be corrupted. Trying again.

I am using following dependencies :-
![image](https://user-images.githubusercontent.com/65001074/127490405-4cbceef6-cd06-40eb-8d7f-d4dddd216bd9.png)

Error:-
![image](https://user-images.githubusercontent.com/65001074/127490612-d7e25665-dcaf-4dd6-a4ca-bcc78cc5d9b2.png)

**Comment by mcollina** [comment]
This seems a problem with npm itself. I've installed this module plenty of time and it never caused issues.
