### ISSUE TITLE
Adding default options breaks the Internet

### ISSUE THREAD

**Issue by dpodsiadlo** [davidmarkclements/fast-safe-stringify#60]
Hi, in the latest release you're introducing defaultLimits which haven't existed before: https://github.com/davidmarkclements/fast-safe-stringify/compare/v2.0.8...v2.1.0#diff-e727e4bdf3657fd1d798edcd6b099d6e092f8573cba266154583a746bba0f346R22 

This might break the Internet because of superagent lib using safe-fast-stringify ^2.0.7 and not providing any limits to the stringify method.

**Comment by mcollina** [comment]
This was _already_ fixed in #58

**Comment by dpodsiadlo** [comment]
Any plans on releasing the fix?

**Comment by mcollina** [comment]
I released it 1 hour ago.

**Comment by dpodsiadlo** [comment]
thank you very much!
