### ISSUE TITLE
Type module support

### ISSUE THREAD

**Issue by gustawdaniel** [davidmarkclements/fast-safe-stringify#65]
I have `type: module` in package.json

Now I am using

```
import safeStringify from 'fast-safe-stringify';
```

and

```
safeStringify.default(incident)
```

I would prefer to hide this `.defaut` in the library code so it should be built as esm and cjs version.

**Comment by mcollina** [comment]
Would you like to send a PR to add a `module.exports.stringify = safeStringify`?
